### ISSUE TITLE
Android: Com.OneSignal 3.1.1 is not really compatible with Xamarin.GooglePlayServices.Gcm 60.1142.1

### ISSUE THREAD

**Issue by rwasef1830** [OneSignal/OneSignal-Xamarin-SDK#101]
**Description:**

Com.OneSignal 3.1.1 is not really compatible with Xamarin.GooglePlayServices.Gcm 60.1142.1

When you build an app with the above packages, the app will fail to register with OneSignal and the following error will appear in the android log (during the StartInit() / EndInit() calls):

```
05-29 17:42:14.453 E/OneSignal(17498): Error Getting Google Registration ID
05-29 17:42:14.453 E/OneSignal(17498): java.lang.NoSuchMethodError: No static method zzbz(Landroid/content/Context;)Z in class Lcom/google/android/gms/iid/zzc; or its super classes (declaration of 'com.google.android.gms.iid.zzc' appears in /data/app/com.companyname-1/base.apk)
05-29 17:42:14.453 E/OneSignal(17498):  at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
05-29 17:42:14.453 E/OneSignal(17498):  at com.onesignal.PushRegistratorGPS$2.run(PushRegistratorGPS.java:168)
05-29 17:42:14.453 E/OneSignal(17498):  at java.lang.Thread.run(Thread.java:761)
```
It appears to be an ABI breaking change in the com.google.android.gms.iid library used by the newer 60.x NuGet package and OneSignal 3.1.1 is not binary compatible with it.

Downgrading to Xamarin.GooglePlayServices.Gcm version 42.1021.1 and rebuilding the application (after purging bin/obj folders and close reopen the solution) will cause it to register successfully with OneSignal and the above error will not appear.

```
05-29 17:54:05.227 I/OneSignal(18695): Device registered, Google Registration ID = XXXXXX
```

**Test Environment**
1. Xamarin SDK that comes with Visual Studio 2017 15.7.2 Update
2. Xamarin Forms version 3.0.0.482510
3. Android Platform SDK 27
4. Tested on real device running Android 7.1 and also Android Simulator running 7.1. Reproducible in both.

Hope this helps someone.

**Comment by Nightsd01** [comment]
@rwasef1830 can you tell me if you still see this issue in our latest update (3.2.0)?

**Comment by rwasef1830** [comment]
No change:

```
06-03 01:10:41.185 E/OneSignal(21506): Unknown error getting GCM Token
06-03 01:10:41.185 E/OneSignal(21506): java.lang.NoSuchMethodError: No static method zzbz(Landroid/content/Context;)Z in class Lcom/google/android/gms/iid/zzc; or its super classes (declaration of 'com.google.android.gms.iid.zzc' appears in /data/app/com.sabat.vendor-1/base.apk)
06-03 01:10:41.185 E/OneSignal(21506): 	at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
06-03 01:10:41.185 E/OneSignal(21506): 	at com.onesignal.PushRegistratorGCM.getToken(PushRegistratorGCM.java:42)
06-03 01:10:41.185 E/OneSignal(21506): 	at com.onesignal.PushRegistratorAbstractGoogle.attemptRegistration(PushRegistratorAbstractGoogle.java:97)
06-03 01:10:41.185 E/OneSignal(21506): 	at com.onesignal.PushRegistratorAbstractGoogle.access$100(PushRegistratorAbstractGoogle.java:37)
06-03 01:10:41.185 E/OneSignal(21506): 	at com.onesignal.PushRegistratorAbstractGoogle$1.run(PushRegistratorAbstractGoogle.java:84)
06-03 01:10:41.185 E/OneSignal(21506): 	at java.lang.Thread.run(Thread.java:761)
```

In addition I just noticed this art error as well (might have been in the previous version also):
```
06-03 01:10:40.043 I/art     (21506): Rejecting re-init on previously-failed class java.lang.Class<com.onesignal.LocationGMS$LocationUpdateListener>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/location/LocationListener;
06-03 01:10:40.043 I/art     (21506):   at void com.onesignal.LocationGMS.onFocusChange() (LocationGMS.java:293)
06-03 01:10:40.043 I/art     (21506):   at void com.onesignal.OneSignal.onAppFocus() (OneSignal.java:1112)
06-03 01:10:40.043 I/art     (21506):   at void com.onesignal.ActivityLifecycleHandler.handleFocus() (ActivityLifecycleHandler.java:120)
06-03 01:10:40.044 I/art     (21506):   at void com.onesignal.ActivityLifecycleHandler.onActivityResumed(android.app.Activity) (ActivityLifecycleHandler.java:74)
06-03 01:10:40.044 I/art     (21506):   at void com.onesignal.ActivityLifecycleListener.onActivityResumed(android.app.Activity) (ActivityLifecycleListener.java:48)
06-03 01:10:40.044 I/art     (21506):   at void android.app.Application.dispatchActivityResumed(android.app.Activity) (Application.java:216)
06-03 01:10:40.044 I/art     (21506):   at void android.app.Activity.onResume() (Activity.java:1251)
06-03 01:10:40.044 I/art     (21506):   at void android.support.v4.app.FragmentActivity.onResume() (FragmentActivity.java:458)
06-03 01:10:40.044 I/art     (21506):   at void md51558244f76c53b6aeda52c8a337f2c37.FormsAppCompatActivity.n_onResume() (FormsAppCompatActivity.java:-2)
06-03 01:10:40.044 I/art     (21506):   at void md51558244f76c53b6aeda52c8a337f2c37.FormsAppCompatActivity.onResume() (FormsAppCompatActivity.java:112)
06-03 01:10:40.044 I/art     (21506):   at void android.app.Instrumentation.callActivityOnResume(android.app.Activity) (Instrumentation.java:1269)
06-03 01:10:40.044 I/art     (21506):   at void android.app.Activity.performResume() (Activity.java:6783)
06-03 01:10:40.044 I/art     (21506):   at android.app.ActivityThread$ActivityClientRecord android.app.ActivityThread.performResumeActivity(android.os.IBinder, boolean, java.lang.String) (ActivityThread.java:3406)
06-03 01:10:40.044 I/art     (21506):   at void android.app.ActivityThread.handleResumeActivity(android.os.IBinder, boolean, boolean, boolean, int, java.lang.String) (ActivityThread.java:3469)
06-03 01:10:40.044 I/art     (21506):   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2732)
06-03 01:10:40.044 I/art     (21506):   at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
06-03 01:10:40.044 I/art     (21506):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1477)
06-03 01:10:40.044 I/art     (21506):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
06-03 01:10:40.044 I/art     (21506):   at void android.os.Looper.loop() (Looper.java:154)
06-03 01:10:40.044 I/art     (21506):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6119)
06-03 01:10:40.044 I/art     (21506):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
06-03 01:10:40.044 I/art     (21506):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:886)
06-03 01:10:40.044 I/art     (21506):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:776)
06-03 01:10:40.044 I/art     (21506): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.location.LocationListener" on path: DexPathList[[zip file "/data/app/com.sabat.vendor-1/base.apk"],nativeLibraryDirectories=[/data/app/com.sabat.vendor-1/lib/x86, /system/fake-libs, /data/app/com.sabat.vendor-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
06-03 01:10:40.044 I/art     (21506):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
06-03 01:10:40.044 I/art     (21506):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
06-03 01:10:40.044 I/art     (21506):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
06-03 01:10:40.044 I/art     (21506):   at void com.onesignal.LocationGMS.onFocusChange() (LocationGMS.java:293)
06-03 01:10:40.044 I/art     (21506):   at void com.onesignal.OneSignal.onAppFocus() (OneSignal.java:1112)
06-03 01:10:40.044 I/art     (21506):   at void com.onesignal.ActivityLifecycleHandler.handleFocus() (ActivityLifecycleHandler.java:120)
06-03 01:10:40.044 I/art     (21506):   at void com.onesignal.ActivityLifecycleHandler.onActivityResumed(android.app.Activity) (ActivityLifecycleHandler.java:74)
06-03 01:10:40.044 I/art     (21506):   at void com.onesignal.ActivityLifecycleListener.onActivityResumed(android.app.Activity) (ActivityLifecycleListener.java:48)
06-03 01:10:40.044 I/art     (21506):   at void android.app.Application.dispatchActivityResumed(android.app.Activity) (Application.java:216)
06-03 01:10:40.044 I/art     (21506):   at void android.app.Activity.onResume() (Activity.java:1251)
06-03 01:10:40.044 I/art     (21506):   at void android.support.v4.app.FragmentActivity.onResume() (FragmentActivity.java:458)
06-03 01:10:40.044 I/art     (21506):   at void md51558244f76c53b6aeda52c8a337f2c37.FormsAppCompatActivity.n_onResume() (FormsAppCompatActivity.java:-2)
06-03 01:10:40.044 I/art     (21506):   at void md51558244f76c53b6aeda52c8a337f2c37.FormsAppCompatActivity.onResume() (FormsAppCompatActivity.java:112)
06-03 01:10:40.044 I/art     (21506):   at void android.app.Instrumentation.callActivityOnResume(android.app.Activity) (Instrumentation.java:1269)
06-03 01:10:40.044 I/art     (21506):   at void android.app.Activity.performResume() (Activity.java:6783)
06-03 01:10:40.044 I/art     (21506):   at android.app.ActivityThread$ActivityClientRecord android.app.ActivityThread.performResumeActivity(android.os.IBinder, boolean, java.lang.String) (ActivityThread.java:3406)
06-03 01:10:40.044 I/art     (21506):   at void android.app.ActivityThread.handleResumeActivity(android.os.IBinder, boolean, boolean, boolean, int, java.lang.String) (ActivityThread.java:3469)
06-03 01:10:40.044 I/art     (21506):   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2732)
06-03 01:10:40.044 I/art     (21506):   at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
06-03 01:10:40.045 I/art     (21506):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1477)
06-03 01:10:40.045 I/art     (21506):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
06-03 01:10:40.045 I/art     (21506):   at void android.os.Looper.loop() (Looper.java:154)
06-03 01:10:40.045 I/art     (21506):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6119)
06-03 01:10:40.045 I/art     (21506):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
06-03 01:10:40.045 I/art     (21506):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:886)
06-03 01:10:40.045 I/art     (21506):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:776)
06-03 01:10:40.045 I/art     (21506): 
```
Though that error might be due to running in emulator or irrelevant. I'm not sure.

**Comment by EmilAlipiev** [comment]
isnt that proguard error?

**Comment by rwasef1830** [comment]
That's with a default fresh project. ProGuard not enabled.

**Comment by jkasten2** [comment]
@rwasef1830 These `NoSuchMethodError` errors on some obfuscated class means you are missing a dependency in your project or you have a mixture of different package versions.  In your case since you updated I believe this is due to a mixture of different versions of `Xarmarin.GooglePlayServices` packages in your project. If you update one of them you will need to update them all.

**Comment by EmilAlipiev** [comment]
@jkasten2  this is related to this issue here https://github.com/OneSignal/OneSignal-Xamarin-SDK/issues/105#issuecomment-398260427

**Comment by jkasten2** [comment]
@EmilAlipiev Yes, if you update `Xamarin.Android.Support` you should make sure each of the package are the same version. Same goes for `Xarmarin.GooglePlayServices` as I noted above otherwise you could get runtime error as rwasef1830 noted.
