### ISSUE TITLE
 FATAL EXCEPTION: Firebase-TokenService

### ISSUE THREAD

**Issue by srdmnc** [OneSignal/OneSignal-Xamarin-SDK#170]
**Description:**

App crashes on **FIRST RUN** due to  **FATAL EXCEPTION: Firebase-TokenService**. But when opening the app again (after the crash), everything works fine. This might have to do with the initialization of the "FirebaseApp" in the SDK (?) I'm not really sure.  I already tried surrounding the  OneSignal.Current.StartInit("app_id").EndInit() in a try-catch but the error/crash still persist.

**Environment**

1. 3.5.0
2. nuget

**Steps to Reproduce Issue:**

 1. Add version 3.5.0 of the Xamarin SDK to your project
  2. Initialize the SDK with App ID
  3. Run the app (first run/install) 

**Anything else:**
```MonoDroid] **UNHANDLED EXCEPTION:**
[MonoDroid] Java.Lang.IllegalStateException: Default FirebaseApp is not initialized in this process package_name. Make sure to call FirebaseApp.initializeApp(Context) first.
[MonoDroid]   at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <xxx>:0 
[MonoDroid]   at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <xxx>:0 
[MonoDroid]   at Firebase.Iid.FirebaseInstanceId.get_Instance () [0x0000a] in <xxx>:0 
[MonoDroid]   at Microsoft.AppCenter.Push.TokenService.OnTokenRefresh () [0x00005] in <xxx>:0 
[MonoDroid]   at Firebase.Iid.FirebaseInstanceIdService.n_OnTokenRefresh (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <xxx>:0 
[MonoDroid]   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.83(intptr,intptr)
[MonoDroid]   --- End of managed Java.Lang.IllegalStateException stack trace ---
[MonoDroid] java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process package_name. Make sure to call FirebaseApp.initializeApp(Context) first.
[MonoDroid] 	at com.google.firebase.FirebaseApp.getInstance(Unknown Source:45)
[MonoDroid] 	at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source:0)
[MonoDroid] 	at xxx.TokenService.n_onTokenRefresh(Native Method)
[MonoDroid] 	at xxx.TokenService.onTokenRefresh(Unknown Source:0)
[MonoDroid] 	at com.google.firebase.iid.FirebaseInstanceIdService.zzd(Unknown Source:12)
[MonoDroid] 	at com.google.firebase.iid.zzg.run(Unknown Source:24)
[MonoDroid] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
[MonoDroid] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
[MonoDroid] 	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
[MonoDroid] 	at java.lang.Thread.run(Thread.java:764)

[AndroidRuntime] **FATAL EXCEPTION:** Firebase-TokenService
[AndroidRuntime] Process: package_name, PID: ###
[AndroidRuntime] java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process package_name. Make sure to call FirebaseApp.initializeApp(Context) first.
[AndroidRuntime] 	at com.google.firebase.FirebaseApp.getInstance(Unknown Source:45)
[AndroidRuntime] 	at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source:0)
[AndroidRuntime] 	at xxx.TokenService.n_onTokenRefresh(Native Method)
[AndroidRuntime] 	at xxx.TokenService.onTokenRefresh(Unknown Source:0)
[AndroidRuntime] 	at com.google.firebase.iid.FirebaseInstanceIdService.zzd(Unknown Source:12)
[AndroidRuntime] 	at com.google.firebase.iid.zzg.run(Unknown Source:24)
[AndroidRuntime] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
[AndroidRuntime] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
[AndroidRuntime] 	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
[AndroidRuntime] 	at java.lang.Thread.run(Thread.java:764)
[OneSignal] Device registered, UserId =user_id

**Comment by srdmnc** [comment]
Anyone there?

**Comment by rgomezp** [comment]
1) Please include your gradle file
2) Are you using another Firebase project in your app?

**Comment by srdmnc** [comment]
@rgomezp 

1. This is a Xamarin forms project, there is no Gradle file.
2. No, I'm not using another Firebase project in my app.

**Comment by jkasten2** [comment]
@srdmnc I do see `Microsoft.AppCenter.Push.TokenService.OnTokenRefresh` in the stacktrace of your crash and not OneSignal. If you don't need to use App Center push with OneSignal at the same time can you disable AppCenter push by removing it or disabling it in another way?

**Comment by srdmnc** [comment]
@jkasten2 Oh, I missed that. Removing `Microsoft.AppCenter.Push` solved this issue. 

Thanks!
