### ISSUE TITLE
OneSignalRestClient: null Error thrown from network stack.

### ISSUE THREAD

**Issue by pbiajoni** [OneSignal/OneSignal-Xamarin-SDK#200]
**Description:**
The SDK tries to connect an address that does not exist

1. SDK Version 3.8.2
2. Configuration->OneSignal.Current.StartInit("myappid")
              .Settings(new Dictionary<string, bool>() {
                { IOSSettings.kOSSettingsKeyAutoPrompt, false },
                { IOSSettings.kOSSettingsKeyInAppLaunchURL, false } }).UnsubscribeWhenNotificationsAreDisabled(true)
                .InFocusDisplaying(OSInFocusDisplayOption.Notification)
              .EndInit();
3. My log shows the attempt to connect to the url https://api.onesignal.com/apps/[MyAppID]/android_params.js and returns the error(and does not generate subscriptions)

When a try to access this url in browser the url changes from https://**api.onesignal.com**/apps/[MyAppID]/android_params.js to https://**app.api.onesignal.com**/apps/[MyAppID]/android_params.js and the answer is "Server not found" .

OneSignalRestClient: Making request to: https://api.onesignal.com/apps/[MyAppID]/android_params.js
05-25 11:54:51.535 W/OneSignal( 5082): OneSignalRestClient: null Error thrown from network stack. 
05-25 11:54:51.535 W/OneSignal( 5082): javax.net.ssl.SSLHandshakeException: Chain validation failed
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:229)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.onesignal.OneSignalRestClient.startHTTPConnection(OneSignalRestClient.java:180)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.onesignal.OneSignalRestClient.access$100(OneSignalRestClient.java:44)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.onesignal.OneSignalRestClient$4.run(OneSignalRestClient.java:110)
05-25 11:54:51.535 W/OneSignal( 5082): 	at java.lang.Thread.run(Thread.java:764)
05-25 11:54:51.535 W/OneSignal( 5082): Caused by: java.security.cert.CertificateException: Chain validation failed
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:707)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:539)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:560)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:605)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339)
05-25 11:54:51.535 W/OneSignal( 5082): 	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
05-25 11:54:51.535 W/OneSignal( 5082): 	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:208)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:404)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
05-25 11:54:51.535 W/OneSignal( 5082): 	... 17 more
05-25 11:54:51.535 W/OneSignal( 5082): Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
05-25 11:54:51.535 W/OneSignal( 5082): 	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
05-25 11:54:51.535 W/OneSignal( 5082): 	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:222)
05-25 11:54:51.535 W/OneSignal( 5082): 	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
05-25 11:54:51.535 W/OneSignal( 5082): 	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
05-25 11:54:51.535 W/OneSignal( 5082): 	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
05-25 11:54:51.535 W/OneSignal( 5082): 	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:703)
05-25 11:54:51.535 W/OneSignal( 5082): 	... 30 more
05-25 11:54:51.535 W/OneSignal( 5082): Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
05-25 11:54:51.536 W/OneSignal( 5082): 	at sun.security.provider.certpath.OCSPResponse.verify(OCSPResponse.java:619)
05-25 11:54:51.536 W/OneSignal( 5082): 	at sun.security.provider.certpath.RevocationChecker.checkOCSP(RevocationChecker.java:709)
05-25 11:54:51.536 W/OneSignal( 5082): 	at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:363)
05-25 11:54:51.536 W/OneSignal( 5082): 	at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:337)
05-25 11:54:51.536 W/OneSignal( 5082): 	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
05-25 11:54:51.536 W/OneSignal( 5082): 	... 35 more
05-25 11:54:51.536 W/OneSignal( 5082): 	Suppressed: java.security.cert.CertPathValidatorException: Could not determine revocation status
05-25 11:54:51.536 W/OneSignal( 5082): 		at sun.security.provider.certpath.RevocationChecker.buildToNewKey(RevocationChecker.java:1092)
05-25 11:54:51.536 W/OneSignal( 5082): 		at sun.security.provider.certpath.RevocationChecker.verifyWithSeparateSigningKey(RevocationChecker.java:910)
05-25 11:54:51.536 W/OneSignal( 5082): 		at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:577)
05-25 11:54:51.536 W/OneSignal( 5082): 		at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:465)
05-25 11:54:51.536 W/OneSignal( 5082): 		at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:394)
05-25 11:54:51.536 W/OneSignal( 5082): 		... 37 more
05-25 11:54:51.545 I/OneSignal( 5082): Failed to get Android parameters, trying again in 40 seconds.

**Comment by pbiajoni** [comment]
Its working in production (GooglePlay)
