### ISSUE TITLE
Notifications Not Shown Xamarin Forms Android

### ISSUE THREAD

**Issue by rrockerr** [OneSignal/OneSignal-Xamarin-SDK#202]
My app showing local notifications, and showing in-app message, but dosen't show push notifications. 

I try release and debug mode with emulator and physical device. Dosen't show notifications. 

I just noticed this situation
```

> 06-07 19:18:35.085 E/FirebaseInstanceId(21320): Token retrieval failed: SERVICE_NOT_AVAILABLE
> 06-07 19:18:35.085 I/OneSignal(21320): 'Google Play services' returned SERVICE_NOT_AVAILABLE error. Current retry count: 0
> 06-07 19:18:35.085 I/OneSignal(21320): java.io.IOException: SERVICE_NOT_AVAILABLE
> 06-07 19:18:35.085 I/OneSignal(21320): 	at com.google.firebase.iid.zzr.zza(Unknown Source)
> 06-07 19:18:35.085 I/OneSignal(21320): 	at com.google.firebase.iid.zzr.zza(Unknown Source)
> 06-07 19:18:35.085 I/OneSignal(21320): 	at com.google.firebase.iid.zzu.then(Unknown Source)
> 06-07 19:18:35.085 I/OneSignal(21320): 	at com.google.android.gms.tasks.zzd.run(Unknown Source)
> 06-07 19:18:35.085 I/OneSignal(21320): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
> 06-07 19:18:35.085 I/OneSignal(21320): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
> 06-07 19:18:35.085 I/OneSignal(21320): 	at java.lang.Thread.run(Thread.java:762)
> 06-07 19:19:06.749 E/cr_PlatformSer-Internal(21320): UsageReporting query failed

```

**Comment by rrockerr** [comment]
I solved the problem. the problem is not related to oneSignal or firebase.  Notifications are not shown when I am connected to the wi-fi associated with my ISP. Notifications are shown when using mobile data.
