### ISSUE TITLE
NotificationExtenderService no Extender prop at OverrideSettings

### ISSUE THREAD

**Issue by man0rei** [OneSignal/OneSignal-Xamarin-SDK#231]
**Description:**

I try to implement Android Notification Extender Service to change payload as it is described at https://documentation.onesignal.com/docs/service-extensions#notification-extender-service and also using this snippet https://github.com/OneSignal/OneSignal-Xamarin-SDK/issues/123#issuecomment-447792361

`
[Service(Permission = "android.permission.BIND_JOB_SERVICE", Exported = false)]
    [IntentFilter(actions: new[] {"com.onesignal.NotificationExtender"})]
    public sealed class OneSignalNotificationExtenderService : NotificationExtenderService
    {
        static readonly OverrideSettings _displaySettings = new OverrideSettings() {Extender = new Extender()};

        protected override bool OnNotificationProcessing(OSNotificationReceivedResult p0)
        {
            var notification = Com.OneSignal.NotificationOpenedHandler.OSNotificationToNative(new OSNotification() {Payload = p0.Payload});

            DisplayNotification(_displaySettings);

            // task.Wait();
            return true;
        }
        
        protected override void OnHandleIntent(Intent intent)
        {
        }

        private sealed class ExtenderEx : Java.Lang.Object, NotificationCompat.IExtender
        {
            public NotificationCompat.Builder Extend(NotificationCompat.Builder builder)
            {
                return builder
                    .SetContentTitle("modified")
                    .SetContentText("modified")
                    // .SetDefaults(~(int) NotificationDefaults.Sound);
            }
        }
    }
`

.. and having such problems:

**- in ver 3.10.4 there is no property Extender on class OverrideSettings (some binding attr problem, because in .aar such a field exists);
- in ver 3.10.3 and older property Extender exists, but throws Java.Lang.NoSuchFieldError exception** 

**Environment**
1. Targeting Android 10.0 API 29
2. AndroidX.Migration packages are installed

**3.10.3 and older crash stacktrace**

Java.Lang.NoSuchFieldError: no type "Landroid/support/v4/app/NotificationCompat$Extender;" found and so no field "extender" could be found in class "Lcom/onesignal/NotificationExtenderService$OverrideSettings;" or its superclasses ---> Java.Lang.ClassNotFoundException: Didn't find class "android.support.v4.app.NotificationCompat$Extender" on path: DexPathList[[zip file "/data/app/com.tawasal.campus.mobile-O1CPsJ29_qaKpD3YgqcOmw==/base.apk"],nativeLibraryDirectories=[/data/app/com.tawasal.campus.mobile-O1CPsJ29_qaKpD3YgqcOmw==/lib/arm, /data/app/com.tawasal.campus.mobile-O1CPsJ29_qaKpD3YgqcOmw==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
   --- End of inner exception stack trace ---
  at Java.Interop.JniEnvironment+InstanceFields.GetFieldID (Java.Interop.JniObjectReference type, System.String name, System.String signature) [0x0005b] in <8b3b636835d84984ba4604c1f57b1983>:0 
  at Java.Interop.JniType.GetInstanceField (System.String name, System.String signature) [0x0000c] in <8b3b636835d84984ba4604c1f57b1983>:0 
  at Java.Interop.JniPeerMembers+JniInstanceFields.GetFieldInfo (System.String encodedMember) [0x00036] in <8b3b636835d84984ba4604c1f57b1983>:0 
  at Java.Interop.JniPeerMembers+JniInstanceFields.SetValue (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniObjectReference value) [0x00006] in <8b3b636835d84984ba4604c1f57b1983>:0 
  at Com.OneSignal.Android.NotificationExtenderService+OverrideSettings.set_Extender (AndroidX.Core.App.NotificationCompat+IExtender value) [0x00007] in /Users/josh/Documents/repos/OneSignal-Xamarin-SDK/OneSignal.Android.Binding/obj/Release/generated/src/Com.OneSignal.Android.NotificationExtenderService.cs:54 
  at CampusMobile.Droid.Services.OneSignalNotificationExtenderService.OnNotificationProcessing (Com.OneSignal.Android.OSNotificationReceivedResult p0) [0x0001f] in /Users/m/dev/repo/campus-mobile-xf/CampusMobile/CampusMobile/CampusMobile.Android/Services/OneSignalNotificationExtenderService.cs:27 
  at Com.OneSignal.Android.NotificationExtenderService.n_OnNotificationProcessing_Lcom_onesignal_OSNotificationReceivedResult_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_p0) [0x00011] in /Users/josh/Documents/repos/OneSignal-Xamarin-SDK/OneSignal.Android.Binding/obj/Release/generated/src/Com.OneSignal.Android.NotificationExtenderService.cs:295 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.104(intptr,intptr,intptr)
  --- End of managed Java.Lang.NoSuchFieldError stack trace ---
java.lang.NoSuchFieldError: no type "Landroid/support/v4/app/NotificationCompat$Extender;" found and so no field "extender" could be found in class "Lcom/onesignal/NotificationExtenderService$OverrideSettings;" or its superclasses
	at crc64fee1e6eafa1c956b.OneSignalNotificationExtenderService.n_onNotificationProcessing(Native Method)
	at crc64fee1e6eafa1c956b.OneSignalNotificationExtenderService.onNotificationProcessing(OneSignalNotificationExtenderService.java:30)
	at com.onesignal.NotificationExtenderService.processJsonObject(NotificationExtenderService.java:170)
	at com.onesignal.NotificationExtenderService.processIntent(NotificationExtenderService.java:155)
	at com.onesignal.NotificationExtenderService.onHandleWork(NotificationExtenderService.java:123)
	at com.onesignal.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:439)
	at com.onesignal.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:430)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.NotificationCompat$Extender" on path: DexPathList[[zip file "/data/app/com.tawasal.campus.mobile-O1CPsJ29_qaKpD3YgqcOmw==/base.apk"],nativeLibraryDirectories=[/data/app/com.tawasal.campus.mobile-O1CPsJ29_qaKpD3YgqcOmw==/lib/arm, /data/app/com.tawasal.campus.mobile-O1CPsJ29_qaKpD3YgqcOmw==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)

**Comment by tanaynigam** [comment]
@lltwist Thanks for reporting the issue. We'll be looking into it shortly to see if this is possible with the current OneSignal 4.x.x SDK. If it is we will create a guide for this, if it requires some SDK changes this will take us a bit more to get a working solution.

**Comment by Acilec** [comment]
Any news on this?

Im using OneSignalSDK.Xamarin 4.1.3 and would like to receive remote push messages in the background.

**Comment by tmijieux** [comment]
It looks like NotificationExtender is not available in the code with the new version  `OneSignalSDK.Xamarin; OneSignalSDK.Xamarin.Core;`

while it was in the old deprecated lib `Com.OneSignal` 

This is a rather big issue with my app also because i had a feature where i sent a notification just to wake up the app without displaying any notification band and without playing any sound in the Android UI. Without a customizable service the default behavior of the OneSignal default service is to display the notification.

Is there an alternative? does the native lib paradigm changed so that it cannot be translated anymore in Xamarin ?
If not would you be accepting pull request for this ? 

@brismithers

**Comment by brismithers** [comment]
I believe since v4 of the SDK (and v5 of the [.NET SDK](https://github.com/onesignal/onesignal-dotnet-sdk), which supports both Xamarin and .NET 6+) rely on the service extension documented [here for v4](https://documentation.onesignal.com/v9.0/docs/service-extensions#android-notification-service-extension) and [here for v5](https://documentation.onesignal.com/docs/service-extensions#android-notification-service-extension).  Unfortunately we do not have a .NET-specific solution, but you should be able to create a native Notification Service Extension and implement your logic in java/kotlin.

The primary reason we do not have a .NET-specific solution is the native Android SDK instantiates the class defined in your `AndroidManifest.xml` using reflection ([if interested](https://github.com/OneSignal/OneSignal-Android-SDK/blob/user-model/main/OneSignalSDK/onesignal/notifications/src/main/java/com/onesignal/notifications/internal/lifecycle/impl/NotificationLifecycleService.kt#L138)).  We have not yet been able to come up with an elegant way for the Android native/.NET SDK to instantiate and call your Notification Service Extension within the Xamarin runtime (xamarin creates dynamic package names are dynamic, [here's some docs](https://learn.microsoft.com/en-us/xamarin/android/platform/java-integration/android-callable-wrappers#android-callable-wrapper-naming) describing how you can define an Activity with a predictable name that can be referenced in the `AndroidManifest.xml`).

We would absolutely be receptive to ideas from the Xamarin/.NET community on how best to tackle this to make it easier to get control on cold start, as we realize this is a common scenario and "going native" is not ideal.

**Comment by tmijieux** [comment]
after looking up my old code, the code that i had working was a little different: it was using an intent filter with a service directly

```xml
    <service android:name="com.my.app.NotificationExtender" android:permission="android.permission.BIND_JOB_SERVICE" android:exported="false">
      <intent-filter>
	<action android:name="com.onesignal.NotificationExtender" />
      </intent-filter>
    </service>
```

```cs
using System;
using Android.App;
using Android.Content;
using Com.OneSignal.Android;
using Serilog;

namespace MyApp.Droid
{
    [Service(Name = "com.my.app.NotificationExtender")]
    public class NotificationExtender : NotificationExtenderService
    {
        protected override void OnHandleIntent(Intent intent) { }

        protected override bool OnNotificationProcessing(OSNotificationReceivedResult receivedResult)
        {
            if (receivedResult == null
                || receivedResult.Payload == null
                || receivedResult.Payload.AdditionalData == null)
            {
                return false;
            }
            var payload = receivedResult.Payload;
            bool ret = false;
            try
            {
                var discard = payload.AdditionalData.Get("silent");
                if (discard != null)
                {
                    ret = true;
                }
                payload.AdditionalData.Put("datetimeReceived", (string)DateTime.UtcNow.ToString("o"));
            }
            catch (Exception /*e*/)
            {
            }
            return ret;
        }
    }
}
```


but still, the service was able to start like a regular service  so i cannot (yet?) see why there should be a problem instanciating it with introspection from javaworld. I will try to do it and tell my results here.

**Comment by tmijieux** [comment]
Hi,@brismithers  i submitted this  PR https://github.com/OneSignal/OneSignal-Xamarin-SDK/pull/381  regarding what we discussed. Could you check if this would do the trick for you ?
