### ISSUE TITLE
Location permission exists but there was an error initializing.

### ISSUE THREAD

**Issue by William-H-M** [OneSignal/OneSignal-Xamarin-SDK#37]
Hi, I'm getting the following error.

What I know about it is that:
1) This has happened because I installed the plugin [Xam.Plugin.Geolocator](https://github.com/jamesmontemagno/xamarin.plugins) which install by default [Plugin.Permissions](https://github.com/jamesmontemagno/PermissionsPlugin) and [Plugin.CurrentActivity](https://github.com/jamesmontemagno/CurrentActivityPlugin)

2) AFAIK The problem happen because

a)
> This warning is from the OneSignal SDK trying to connect to Google Play services to get the device's location but it timed out due to mixed versions of Google Play services included in the app or when the device is offline in some cases.
[Source](http://stackoverflow.com/a/35144900)

b)
Because of OneSignal clash with the permissions asked by the Plugin.Permissions
which is what I understood by the logged error on this [forum ](https://forums.coronalabs.com/topic/60933-clash-between-onesignal-and-location-on-android/)

c)
Related to #140 of [Android SDK](https://github.com/OneSignal/OneSignal-Android-SDK/issues/140)

In which the solution was to add
`compile "com.google.android.gms:play-services-location:+"`

But not sure were to add this on a Xamarin.Forms project.

For me it looks like if it's ab<receiver/> but not sure of it.

Error:
```
Location permission exists but there was an error initializing: 
 java.lang.NoClassDefFoundError: com.google.android.gms.location.LocationServices
 	at com.onesignal.LocationGMS.startGetLocation(LocationGMS.java:117)
 	at com.onesignal.LocationGMS.getLocation(LocationGMS.java:79)
	at com.onesignal.OneSignal.startLocationUpdate(OneSignal.java:327)
	at com.onesignal.OneSignal.startRegistrationOrOnSession(OneSignal.java:319)
	at com.onesignal.OneSignal.onAppFocus(OneSignal.java:587)
	at com.onesignal.ActivityLifecycleHandler.handleFocus(ActivityLifecycleHandler.java:120)
	at com.onesignal.ActivityLifecycleHandler.onActivityResumed(ActivityLifecycleHandler.java:74)
	at com.onesignal.ActivityLifecycleListener.onActivityResumed(ActivityLifecycleListener.java:50)
 	at android.app.Application.dispatchActivityResumed(Application.java:223)
	at android.app.Activity.onResume(Activity.java:1111)
 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
 	at android.app.Activity.performResume(Activity.java:5312)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3002)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3041)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2393)
	at android.app.ActivityThread.access$900(ActivityThread.java:148)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5457)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
	at dalvik.system.NativeStart.main(Native Method)
```
So it's any way to stop the error or at least stop the alert showing because it doesn't affect on anything the flow of the system nor cause any other error but for a normal user this will appear everytime the app is open and will be annoying or scary.

**EDIT:** As for now I've stopped the alert changing the following on the SharedPush class

           `OneSignal.Current.SetLogLevel(LOG_LEVEL.VERBOSE, LOG_LEVEL.WARN);`
to
           `OneSignal.Current.SetLogLevel(LOG_LEVEL.VERBOSE, LOG_LEVEL.NONE);`

[Source](https://documentation.onesignal.com/v3.0/docs/xamarin-sdk#section--setloglevel-)

Thanks for any help granted.

**Comment by jkasten2** [comment]
@William-H-M The initialization error is most likely happening due to the Plugin.Permissions library or one of the other ones you listed including a different version of the Google Play services library as the error notes.

You can remove `SetLogLevel` completely from your code and it will default to `(LOG_LEVEL.WARN, LOG_LEVEL.NONE)` which means only warnings and errors will be logged to the logcat but the user will never see any alerts. We will add a comment to the example project code to note this.

Thanks.

**Comment by William-H-M** [comment]
@jkasten2 Yes, I've done that and the problem is mainly coming from Plugin.Permissions library because just after removing the package as a test didn't give any errors. But as is just an alert of different permission usages doesn't effect all the workflow of the system, at least on my case, but yes it'll be a great help to have a comment about it, that way the newbies, like me, doesn't have a weird start.

Thanks for the quick response.
