### ISSUE TITLE
On distrubute app in google play error

### ISSUE THREAD

**Issue by vkurilenko** [OneSignal/OneSignal-Xamarin-SDK#88]
After convert to netstandart project.
On distribute application on google play.
```C#
Failed to read '....Droid\obj\Release\android\assets\OneSignal.Android.Binding.dll' with debugging symbols. Retrying to load it without it. Error details are logged below.
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader) in /Users/builder/data/lanes/5809/a7829590/source/monodroid/external/xamarin-android/external/Java.Interop/external/cecil/Mono.Cecil/ModuleDefinition.cs:line 1090
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters) in /Users/builder/data/lanes/5809/a7829590/source/monodroid/external/xamarin-android/external/Java.Interop/external/cecil/Mono.Cecil/AssemblyReader.cs:line 108
   at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters) in /Users/builder/data/lanes/5809/a7829590/source/monodroid/external/xamarin-android/external/Java.Interop/external/cecil/Mono.Cecil/AssemblyReader.cs:line 83
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters) in /Users/builder/data/lanes/5809/a7829590/source/monodroid/external/xamarin-android/external/Java.Interop/external/cecil/Mono.Cecil/ModuleDefinition.cs:line 1121
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.ReadAssembly(String file) in /Users/builder/data/lanes/5809/a7829590/source/monodroid/external/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:line 137
```

**Comment by jkasten2** [comment]
@vkurilenko Can you provide step by step details of reproducing this error?

**Comment by vkurilenko** [comment]
Build solution
Archive droid project
Dictribute in Google play.

Properties - Android 8.1
Xamarin Forms

**Comment by Nightsd01** [comment]
@vkurilenko please let me know if this new update (3.2.0) resolves this issue for you.

**Comment by vkurilenko** [comment]
Failed to read ..........\Droid\obj\Release\linksrc\OneSignal.Android.Binding.dll with debugging symbols. Retrying to load it without it. Error details are logged below.

**Comment by EmilAlipiev** [comment]
It is related to this one. https://github.com/OneSignal/OneSignal-Xamarin-SDK/issues/79

**Comment by EmilAlipiev** [comment]
It doesnt occurr for me in the latest version do you still see it?

**Comment by rgomezp** [comment]
Hello @vkurilenko ,
Did you manage to resolve? Please tag us and we will reopen the issue if needed
